"""Delete field already seen secret

Revision ID: e5d66c0deef3
Revises: dddd5ce58a27
Create Date: 2025-08-07 22:16:47.895584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5d66c0deef3'
down_revision: Union[str, Sequence[str], None] = 'dddd5ce58a27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'already_seen_secret')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('already_seen_secret', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
