sequenceDiagram
    participant U as User
    participant A as App
    participant S as SSO

    U->>A: GET https://app.example.ru
    A->>A: Проверка JWT + session
    A-->>U: Redirect https://sso.example.ru/login
    U-->>U: Нет логина и пароля
    U->>S: GET https://sso.example.ru/register
    S->>S: Сохраняет email и пароль
    S->>U: Письмо для подтверждения
    U->>S: Подтверждение email
    S->>S: Обновление статуса на email_verified